# Generated by Django 6.0.5 on 2026-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_helprequest_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper_scope',
            field=models.CharField(choices=[('any', 'Open to all'), ('same_nationality', 'Same nationality only'), ('language_match', 'Language match')], default='any', max_length=20),
        ),
    ]
