# Generated by Django 6.0.5 on 2026-05-18 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_helper_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('banking', '🏦 Banking Pro'), ('housing', '🏠 Housing Wiz'), ('sim_card', '📱 SIM Card Expert'), ('legal', '📄 Legal Guide'), ('language', '💬 Language Coach'), ('job_search', '💼 Job Search Pro'), ('community', '🌍 Community Builder')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['badge_type'],
                'unique_together': {('helper', 'badge_type')},
            },
        ),
    ]
